### ISSUE TITLE
验收测试：关于 resize

### ISSUE THREAD

**Issue by CoffeeChou** [eayunstack/Documents#8]
**仍在测试和验证**
- resize 时，不会 resize **基于卷** 启动的虚拟机的 **磁盘**，其他生效；
- 如果用户要调整虚拟机的磁盘，一是 nova 得 resize，二是 cinder 得 extend；
-  boot from image 的虚拟机似乎可以：仍在测试

测试后更改测试文档： https://github.com/eayunstack/Documents/blob/master/test_docs/evaluation_test/manage-vm/resize.md

**Comment by mathslinux** [comment]
这个功能真正使用有一定的麻烦, cinder的resize的话, 不支持 in-use 的volume, 使用起来很麻烦, 下面有一个blueprints, 貌似一直没有实现
https://blueprints.launchpad.net/nova/+spec/online-volume-extend-extension

**Comment by CoffeeChou** [comment]
boot from volume 的虚拟机 resize 的话，磁盘不会生效，测试了以下办法：
1. 将卷的状态修改为 available：
   
   ```
   # cinder reset-state --state available VOLUME_ID
   ```
2. 扩展卷：
   
   ```
   # cinder extend VOLUME_ID 21
   ```
3. 将卷改回 in-use 状态：
   
   ```
   # cinder reset-state --state in-use VOLUME_ID
   ```
4. 登录到虚拟机，使用命令 <code>lsblk</code> 查看

**extend 成功，但在虚拟机里查看，看到磁盘无变化。**

该方案不成功。

**Comment by CoffeeChou** [comment]
补充：但通过 nova stop/start 重启虚拟机后，生效。

但不符合我们想要的结果。

**Comment by CoffeeChou** [comment]
验证完，关闭。详情请看文档

**Comment by CoffeeChou** [comment]
补充：dashboard 上可以用 soft reboot/hard reboot 来重启，直接在虚拟机内执行 reboot 不生效。
